"""clean postgres schema

Revision ID: b1859ea6560d
Revises: 
Create Date: 2026-09-19 21:00:40.757125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1859ea6560d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ASSESSOR', 'CANDIDATE', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED', name='assessmentstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_created_by'), 'assessments', ['created_by'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.String(), nullable=True),
    sa.Column('starter_repository', sa.String(), nullable=True),
    sa.Column('task_type', sa.Enum('BUG_FIX', 'FEATURE', 'REFACTOR', 'DEBUGGING', 'CODE_REVIEW', name='tasktype'), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assessment_id'), 'tasks', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_table('assessment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'ACTIVE', 'PAUSED', 'SUBMITTED', 'EXPIRED', 'EVALUATING', 'COMPLETED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_sessions_assessment_id'), 'assessment_sessions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_candidate_id'), 'assessment_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_id'), 'assessment_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_started_at'), 'assessment_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_status'), 'assessment_sessions', ['status'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('VISIBLE', 'HIDDEN', name='testvisibility'), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_session_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', 'STOPPED', name='agentsessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_assessment_session_id'), 'agent_sessions', ['assessment_session_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_id'), 'agent_sessions', ['id'], unique=False)
    op.create_table('assessment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('SESSION_STARTED', 'FILE_OPENED', 'FILE_EDITED', 'FILE_CREATED', 'FILE_DELETED', 'AI_MESSAGE', 'AI_TOOL_CALL', 'TEST_STARTED', 'TEST_COMPLETED', 'TEST_FAILED', 'TEST_PASSED', 'CODE_CHANGE', 'DEBUGGING', 'GIT_COMMIT', 'SUBMITTED', 'SESSION_EXPIRED', name='eventtype'), nullable=False),
    sa.Column('actor', sa.Enum('CANDIDATE', 'AI', 'SYSTEM', 'ASSESSOR', name='eventactor'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_events_actor'), 'assessment_events', ['actor'], unique=False)
    op.create_index(op.f('ix_assessment_events_assessment_session_id'), 'assessment_events', ['assessment_session_id'], unique=False)
    op.create_index(op.f('ix_assessment_events_event_type'), 'assessment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_assessment_events_id'), 'assessment_events', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_events_timestamp'), 'assessment_events', ['timestamp'], unique=False)
    op.create_table('assessment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_session_id', sa.Integer(), nullable=False),
    sa.Column('task_summary', sa.Text(), nullable=True),
    sa.Column('implementation_summary', sa.Text(), nullable=True),
    sa.Column('testing_summary', sa.Text(), nullable=True),
    sa.Column('ai_usage_summary', sa.Text(), nullable=True),
    sa.Column('debugging_summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('generated_by', sa.Enum('SYSTEM', 'ASSESSMENT_AI', 'ASSESSOR', name='reportgeneratedby'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_session_id')
    )
    op.create_index(op.f('ix_assessment_reports_id'), 'assessment_reports', ['id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PASSED', 'FAILED', 'COMPLETED', name='evalstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('passed_tests', sa.Integer(), nullable=True),
    sa.Column('failed_tests', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('evaluation_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_assessment_session_id'), 'evaluation_runs', ['assessment_session_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_id'), 'evaluation_runs', ['id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_session_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.Enum('REQUIREMENT_INTERACTION', 'CODE_CHANGE', 'AI_ASSISTANCE', 'AI_VALIDATION', 'TESTING', 'DEBUGGING', 'ITERATION', 'FINAL_SUBMISSION', name='evidencetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_event_ids', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_table('git_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_session_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.Column('changed_files', sa.JSON(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('diff_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_git_evidence_assessment_session_id'), 'git_evidence', ['assessment_session_id'], unique=False)
    op.create_index(op.f('ix_git_evidence_commit_hash'), 'git_evidence', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_git_evidence_created_at'), 'git_evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_git_evidence_id'), 'git_evidence', ['id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_session_id', sa.Integer(), nullable=False),
    sa.Column('workspace_path', sa.String(), nullable=False),
    sa.Column('repository_snapshot', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVE', 'LOCKED', 'DESTROYED', name='workspacestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_session_id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', 'TOOL', name='agentrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_agent_session_id'), 'agent_messages', ['agent_session_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_agent_messages_sequence_number'), 'agent_messages', ['sequence_number'], unique=False)
    op.create_table('report_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['assessment_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_evidence_id'), 'report_evidence', ['id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'ERROR', 'TIMEOUT', 'SKIPPED', name='teststatus'), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_evaluation_run_id'), 'test_results', ['evaluation_run_id'], unique=False)
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_status'), 'test_results', ['status'], unique=False)
    op.create_index(op.f('ix_test_results_test_case_id'), 'test_results', ['test_case_id'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_session_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'RUNNING', 'SUCCESS', 'FAILED', 'REJECTED', name='toolcallstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['agent_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tool_calls_agent_session_id'), 'agent_tool_calls', ['agent_session_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_id'), 'agent_tool_calls', ['id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_status'), 'agent_tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_tool_name'), 'agent_tool_calls', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_tool_calls_tool_name'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_status'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_agent_session_id'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_test_results_test_case_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_status'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_evaluation_run_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_report_evidence_id'), table_name='report_evidence')
    op.drop_table('report_evidence')
    op.drop_index(op.f('ix_agent_messages_sequence_number'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_agent_session_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_git_evidence_id'), table_name='git_evidence')
    op.drop_index(op.f('ix_git_evidence_created_at'), table_name='git_evidence')
    op.drop_index(op.f('ix_git_evidence_commit_hash'), table_name='git_evidence')
    op.drop_index(op.f('ix_git_evidence_assessment_session_id'), table_name='git_evidence')
    op.drop_table('git_evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_evaluation_runs_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_assessment_session_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_assessment_reports_id'), table_name='assessment_reports')
    op.drop_table('assessment_reports')
    op.drop_index(op.f('ix_assessment_events_timestamp'), table_name='assessment_events')
    op.drop_index(op.f('ix_assessment_events_id'), table_name='assessment_events')
    op.drop_index(op.f('ix_assessment_events_event_type'), table_name='assessment_events')
    op.drop_index(op.f('ix_assessment_events_assessment_session_id'), table_name='assessment_events')
    op.drop_index(op.f('ix_assessment_events_actor'), table_name='assessment_events')
    op.drop_table('assessment_events')
    op.drop_index(op.f('ix_agent_sessions_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_assessment_session_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_assessment_sessions_status'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_started_at'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_candidate_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_assessment_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assessment_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_created_by'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
