"""evidence_engine

Revision ID: c988c0438006
Revises: b1859ea6560d
Create Date: 2026-09-20 01:41:33.356729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c988c0438006'
down_revision: Union[str, Sequence[str], None] = 'b1859ea6560d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_events', sa.Column('source', sa.String(), nullable=True))
    op.add_column('assessment_events', sa.Column('sequence_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assessment_events_sequence_number'), 'assessment_events', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_assessment_events_source'), 'assessment_events', ['source'], unique=False)
    
    # Add new enum values
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'SESSION_RESUMED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'SESSION_PAUSED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'SESSION_SUBMITTED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'SESSION_TERMINATED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'FILE_SAVED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'PATCH_APPLIED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AI_MESSAGE_SENT'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AI_RESPONSE_RECEIVED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AI_TOOL_PROPOSED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AI_TOOL_APPROVED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AI_TOOL_REJECTED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AI_TOOL_EXECUTED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AI_TOOL_FAILED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'TEST_RUN_STARTED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'TEST_RUN_COMPLETED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'ERROR_DETECTED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'ERROR_INSPECTED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'DEBUG_ATTEMPT'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'DEBUG_RESOLVED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'GIT_STATUS'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'GIT_DIFF_VIEWED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'TASK_VIEWED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'TASK_STARTED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'TASK_COMPLETED'")
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'SUBMISSION_CREATED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_events_source'), table_name='assessment_events')
    op.drop_index(op.f('ix_assessment_events_sequence_number'), table_name='assessment_events')
    op.drop_column('assessment_events', 'sequence_number')
    op.drop_column('assessment_events', 'source')
    # ### end Alembic commands ###
