import json
from agent.tools import AgentTools

def mock_llm_orchestrator(message: str, tools: AgentTools) -> tuple[str, list]:
    """
    Mocks an LLM orchestrator. 
    It parses the user message for keywords and simulates a tool call,
    returning the agent's textual response and a list of tool call records.
    """
    message_lower = message.lower()
    tool_calls = []
    response = ""

    if "list" in message_lower or "files" in message_lower:
        result = tools.list_files()
        tool_calls.append({
            "tool_name": "list_files",
            "arguments": "{}",
            "result": result,
            "success": 1
        })
        response = "I have listed the files in your workspace."
        
    elif "read" in message_lower:
        # Mock extracting path
        path = "src/index.js"
        result = tools.read_file(path)
        tool_calls.append({
            "tool_name": "read_file",
            "arguments": json.dumps({"path": path}),
            "result": result,
            "success": 1
        })
        response = f"I read the file {path}."
        
    elif "write" in message_lower or "save" in message_lower:
        path = "src/new_file.js"
        content = "console.log('generated by agent');"
        result = tools.write_file(path, content)
        tool_calls.append({
            "tool_name": "write_file",
            "arguments": json.dumps({"path": path, "content": content}),
            "result": result,
            "success": 1
        })
        response = f"I wrote {path}."

    elif "test" in message_lower:
        result = tools.run_tests()
        tool_calls.append({
            "tool_name": "run_tests",
            "arguments": "{}",
            "result": result,
            "success": 1
        })
        response = "I ran the tests."
        
    else:
        response = "I am a mock AI agent. Try asking me to 'list files', 'read a file', 'write a file', or 'run tests'."

    return response, tool_calls
